### ISSUE TITLE
Attempt to subtract with overflow

### ISSUE THREAD

**Issue by adrianlshaw** [spieglt/nestur#4]
Nice project! I found a problem and thought you might want this bug report. This is based on commit
ea70b59. I'm a little new to Rust so I can't help much with the diagnosis. 

```~/github/nestur> RUST_BACKTRACE=1 ./target/debug/nestur Legend\ of\ Zelda\,\ The\ \(USA\).nes 
fps: 14
fps: 9
thread 'main' panicked at 'attempt to subtract with overflow', src/apu/square.rs:117:17
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:76
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:60
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1030
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:64
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:196
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:473
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:380
  12: rust_begin_unwind
             at src/libstd/panicking.rs:307
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  14: core::panicking::panic
             at src/libcore/panicking.rs:49
  15: nestur::apu::square::Square::calculate_target_period
             at src/apu/square.rs:117
  16: nestur::apu::square::Square::write_timer_low
             at src/apu/square.rs:146
  17: nestur::apu::Apu::write_reg
             at src/apu/mod.rs:95
  18: nestur::cpu::Cpu::write
             at src/cpu/mod.rs:203
  19: nestur::cpu::opcodes::<impl nestur::cpu::Cpu>::stx
             at src/cpu/opcodes.rs:491
  20: nestur::cpu::Cpu::step
             at src/cpu/mod.rs:174
  21: nestur::main
             at src/main.rs:58
  22: std::rt::lang_start::{{closure}}
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/rt.rs:64
  23: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  24: std::panicking::try::do_call
             at src/libstd/panicking.rs:292
  25: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  26: std::panicking::try
             at src/libstd/panicking.rs:271
  27: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  28: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  29: std::rt::lang_start
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/rt.rs:64
  30: main
  31: __libc_start_main
  32: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by spieglt** [comment]
Thank you and thanks for the report! I noticed the `fps 14` at the top and guessed you were running cargo without the `--release` flag so I ran it in debug mode and found the same issue, as well as another integer overflow. Commit https://github.com/spieglt/nestur/commit/a86e75c0648129cc5f668452bc48734b0c18aaeb should fix it. Please try if you get the chance and also be sure to build or run with the `--release` flag so you get 60FPS.

**Comment by adrianlshaw** [comment]
The fix works btw!
